# Generated by Django 3.1.5 on 2021-01-13 09:11

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('repo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='Add tags to your images', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
